products = [
    {
        "uuid": "3159432b76b2b8cd",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 80,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "b1740fab54843dcc",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "71e87e5cf701b274",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "234c8bcc61648ab4",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Entwurf",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "56285557f945357c",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "9bac44cbb245f7d2",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "90010007b0ebfe74",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "1813e1c698ccf8d1",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Entwurf",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "30f6c342d58f1a9f",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Entwurf",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "82bde1f70ded0030",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "d29738dfa19f628e",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "248473fa0bcb3aa5",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "a241a2f37102fc81",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    },
    {
        "uuid": "e1a24e2bb6364e30",
        "name": "Sägeblatt",
        "description": "Sägeblatt für Harthölzer",
        "type": "SBHH",
        "stammblattbreite": 2.0,
        "plattensitzhoehe": 3.5,
        "plattensitzlaenge": 3.55,
        "plattensitzwinkel": 40.25,
        "schnittbreite": 3.2,
        "aussendurchmesser": 160.50,
        "bohrungsdurchmesser": 18.0,
        "zaehnezahl": 60,
        "status": "Freigegeben",
        "freecad_available": False,
        "preview_available": False,
        "techdraw_available": False,
        "mfg_available": False
    }
]